from selenium import webdriver

brower = webdriver.Chrome()
url = 'http://quote.eastmoney.com/center/gridlist.html#hs_a_board'
brower.get(url)

biaotou = []
xuhao = brower.find_element_by_xpath('//*[@id="table_wrapper-table"]/thead/tr/th[1]/span')
daima = brower.find_element_by_xpath('//*[@id="table_wrapper-table"]/thead/tr/th[2]/span')
mingcheng = brower.find_element_by_xpath('//*[@id="table_wrapper-table"]/thead/tr/th[3]/span')
xiangguanlianjie = brower.find_element_by_xpath('//*[@id="table_wrapper-table"]/thead/tr/th[4]/span')
zuixinjia = brower.find_element_by_xpath('//*[@id="table_wrapper-table"]/thead/tr/th[5]/span')
zhangdiefu = brower.find_element_by_xpath('//*[@id="table_wrapper-table"]/thead/tr/th[6]/span')
zhangdiee = brower.find_element_by_xpath('//*[@id="table_wrapper-table"]/thead/tr/th[7]/span')
chengjiaoliang = brower.find_element_by_xpath('//*[@id="table_wrapper-table"]/thead/tr/th[8]/span')
chengjiaoe = brower.find_element_by_xpath('//*[@id="table_wrapper-table"]/thead/tr/th[9]/span')
zhenfu = brower.find_element_by_xpath('//*[@id="table_wrapper-table"]/thead/tr/th[10]/span')
zuigao = brower.find_element_by_xpath('//*[@id="table_wrapper-table"]/thead/tr/th[11]/span')
zuidi = brower.find_element_by_xpath('//*[@id="table_wrapper-table"]/thead/tr/th[12]/span')
jinkai = brower.find_element_by_xpath('//*[@id="table_wrapper-table"]/thead/tr/th[13]/span')
zuoshou = brower.find_element_by_xpath('//*[@id="table_wrapper-table"]/thead/tr/th[14]/span')
liangbi = brower.find_element_by_xpath('//*[@id="table_wrapper-table"]/thead/tr/th[15]/span')
huanshoulv = brower.find_element_by_xpath('//*[@id="table_wrapper-table"]/thead/tr/th[16]/span')
shiyinglv = brower.find_element_by_xpath('//*[@id="table_wrapper-table"]/thead/tr/th[17]/span')
shijingzhi = brower.find_element_by_xpath('//*[@id="table_wrapper-table"]/thead/tr/th[18]/span')

biaotou.append(xuhao.text)
biaotou.append(daima.text)
biaotou.append(mingcheng.text)
biaotou.append(xiangguanlianjie.text)
biaotou.append(zuixinjia.text)
biaotou.append(zhangdiefu.text)
biaotou.append(zhangdiee.text)
biaotou.append(chengjiaoliang.text)
biaotou.append(chengjiaoe.text)
biaotou.append(zhenfu.text)
biaotou.append(zuigao.text)
biaotou.append(zuidi.text)
biaotou.append(jinkai.text)
biaotou.append(zuoshou.text)
biaotou.append(liangbi.text)
biaotou.append(huanshoulv.text)
biaotou.append(shiyinglv.text)
biaotou.append(shijingzhi.text)

print(biaotou)

brower.close()
